### ISSUE TITLE
Is jraft production-ready?

### ISSUE THREAD

**Issue by winflex** [datatechnology/jraft#7]
Is jraft production-ready?

**Comment by andy-yx-chen** [comment]
@winflex yes and not, for yes, the algorithm implementation is good enough to go production, actually, the copy implementation of C++ cornerstone is used in eBay's paper. for not, you may need to customize it a little bit based on your scenarios, such as having a more sophisticated log store, and maybe, at leader side, have the original request as log cookie so that state machine does not need to deserialize the log entry to apply the request, which is an optimization, but worth.
